.TH razan 6 "8 Jan 2022"
.SH NAME
razan - End-user client messaging application
.SH SYNOPSIS
razan [ -p --port | -v --verbose | -? --usage --help ]
.SH DESCRIPTION
razan is an end-user client messaging applications which users ncurses to created a display displaying incoming and outgoing messages. AES symmetric encryption is used to protect the messages whilst being transferred from one client to another, via a faciliating server which also sets up the initial connection and encryption keys.
.SS Options
.TP
-?, --help, --usage
Displays brief synopsis and the program's parameters 
.TP
-p, --port
Specifies port to connect to (else program default communications over port 4242)
.SH AUTHOR
.TP
Salih Ahmed
.SH REPORTING BUGS
.TP
Please report bugs on the official Github Issues section of the razan repository <https://github.com/daleksla/razan.git>
.SH COPYRIGHT
.TP
Copyright (C) 2022 Salih Ahmed. See LICENSE for details of usage
.SH "SEE ALSO"
razan_server(8)
