.TH razan_server 8 "18 Dec 2022"
.SH NAME
razan_server - Server for razan client messaging application
.SH SYNOPSIS
razan [PORT] [LIMIT] [-? --usage --help]
.SH DESCRIPTION
razan_server - a program resposible for faciliating encrypted local network communication between clients
.SS Options
.TP
-?, --help, --usage
Displays brief synopsis and the program's parameters
.SH AUTHOR
.TP
Salih Ahmed
.SH REPORTING BUGS
.TP
Please report bugs on the official Github Issues section of the razan repository <https://github.com/daleksla/razan.git>
.SH COPYRIGHT
.TP
Copyright (C) 2022 Salih Ahmed. See LICENSE for details of usage
.SH "SEE ALSO"
razan(6)
