# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/salih/code/projects/razan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/salih/code/projects/razan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salih/code/projects/razan/CMakeFiles /home/salih/code/projects/razan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salih/code/projects/razan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named razan_client

# Build rule for target.
razan_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_client
.PHONY : razan_client

# fast build rule for target.
razan_client/fast:
	$(MAKE) -f CMakeFiles/razan_client.dir/build.make CMakeFiles/razan_client.dir/build
.PHONY : razan_client/fast

#=============================================================================
# Target rules for targets named razan_server

# Build rule for target.
razan_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_server
.PHONY : razan_server

# fast build rule for target.
razan_server/fast:
	$(MAKE) -f CMakeFiles/razan_server.dir/build.make CMakeFiles/razan_server.dir/build
.PHONY : razan_server/fast

#=============================================================================
# Target rules for targets named razan_client_chat

# Build rule for target.
razan_client_chat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_client_chat
.PHONY : razan_client_chat

# fast build rule for target.
razan_client_chat/fast:
	$(MAKE) -f CMakeFiles/razan_client_chat.dir/build.make CMakeFiles/razan_client_chat.dir/build
.PHONY : razan_client_chat/fast

#=============================================================================
# Target rules for targets named razan_client_management

# Build rule for target.
razan_client_management: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_client_management
.PHONY : razan_client_management

# fast build rule for target.
razan_client_management/fast:
	$(MAKE) -f CMakeFiles/razan_client_management.dir/build.make CMakeFiles/razan_client_management.dir/build
.PHONY : razan_client_management/fast

#=============================================================================
# Target rules for targets named razan_encryption

# Build rule for target.
razan_encryption: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_encryption
.PHONY : razan_encryption

# fast build rule for target.
razan_encryption/fast:
	$(MAKE) -f CMakeFiles/razan_encryption.dir/build.make CMakeFiles/razan_encryption.dir/build
.PHONY : razan_encryption/fast

#=============================================================================
# Target rules for targets named razan_logger

# Build rule for target.
razan_logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 razan_logger
.PHONY : razan_logger

# fast build rule for target.
razan_logger/fast:
	$(MAKE) -f CMakeFiles/razan_logger.dir/build.make CMakeFiles/razan_logger.dir/build
.PHONY : razan_logger/fast

src/client_chat.o: src/client_chat.cc.o

.PHONY : src/client_chat.o

# target to build an object file
src/client_chat.cc.o:
	$(MAKE) -f CMakeFiles/razan_client_chat.dir/build.make CMakeFiles/razan_client_chat.dir/src/client_chat.cc.o
.PHONY : src/client_chat.cc.o

src/client_chat.i: src/client_chat.cc.i

.PHONY : src/client_chat.i

# target to preprocess a source file
src/client_chat.cc.i:
	$(MAKE) -f CMakeFiles/razan_client_chat.dir/build.make CMakeFiles/razan_client_chat.dir/src/client_chat.cc.i
.PHONY : src/client_chat.cc.i

src/client_chat.s: src/client_chat.cc.s

.PHONY : src/client_chat.s

# target to generate assembly for a file
src/client_chat.cc.s:
	$(MAKE) -f CMakeFiles/razan_client_chat.dir/build.make CMakeFiles/razan_client_chat.dir/src/client_chat.cc.s
.PHONY : src/client_chat.cc.s

src/client_management.o: src/client_management.cc.o

.PHONY : src/client_management.o

# target to build an object file
src/client_management.cc.o:
	$(MAKE) -f CMakeFiles/razan_client_management.dir/build.make CMakeFiles/razan_client_management.dir/src/client_management.cc.o
.PHONY : src/client_management.cc.o

src/client_management.i: src/client_management.cc.i

.PHONY : src/client_management.i

# target to preprocess a source file
src/client_management.cc.i:
	$(MAKE) -f CMakeFiles/razan_client_management.dir/build.make CMakeFiles/razan_client_management.dir/src/client_management.cc.i
.PHONY : src/client_management.cc.i

src/client_management.s: src/client_management.cc.s

.PHONY : src/client_management.s

# target to generate assembly for a file
src/client_management.cc.s:
	$(MAKE) -f CMakeFiles/razan_client_management.dir/build.make CMakeFiles/razan_client_management.dir/src/client_management.cc.s
.PHONY : src/client_management.cc.s

src/encryption.o: src/encryption.cc.o

.PHONY : src/encryption.o

# target to build an object file
src/encryption.cc.o:
	$(MAKE) -f CMakeFiles/razan_encryption.dir/build.make CMakeFiles/razan_encryption.dir/src/encryption.cc.o
.PHONY : src/encryption.cc.o

src/encryption.i: src/encryption.cc.i

.PHONY : src/encryption.i

# target to preprocess a source file
src/encryption.cc.i:
	$(MAKE) -f CMakeFiles/razan_encryption.dir/build.make CMakeFiles/razan_encryption.dir/src/encryption.cc.i
.PHONY : src/encryption.cc.i

src/encryption.s: src/encryption.cc.s

.PHONY : src/encryption.s

# target to generate assembly for a file
src/encryption.cc.s:
	$(MAKE) -f CMakeFiles/razan_encryption.dir/build.make CMakeFiles/razan_encryption.dir/src/encryption.cc.s
.PHONY : src/encryption.cc.s

src/logger.o: src/logger.c.o

.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) -f CMakeFiles/razan_logger.dir/build.make CMakeFiles/razan_logger.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) -f CMakeFiles/razan_logger.dir/build.make CMakeFiles/razan_logger.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) -f CMakeFiles/razan_logger.dir/build.make CMakeFiles/razan_logger.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/razan_client.o: src/razan_client.cc.o

.PHONY : src/razan_client.o

# target to build an object file
src/razan_client.cc.o:
	$(MAKE) -f CMakeFiles/razan_client.dir/build.make CMakeFiles/razan_client.dir/src/razan_client.cc.o
.PHONY : src/razan_client.cc.o

src/razan_client.i: src/razan_client.cc.i

.PHONY : src/razan_client.i

# target to preprocess a source file
src/razan_client.cc.i:
	$(MAKE) -f CMakeFiles/razan_client.dir/build.make CMakeFiles/razan_client.dir/src/razan_client.cc.i
.PHONY : src/razan_client.cc.i

src/razan_client.s: src/razan_client.cc.s

.PHONY : src/razan_client.s

# target to generate assembly for a file
src/razan_client.cc.s:
	$(MAKE) -f CMakeFiles/razan_client.dir/build.make CMakeFiles/razan_client.dir/src/razan_client.cc.s
.PHONY : src/razan_client.cc.s

src/razan_server.o: src/razan_server.cc.o

.PHONY : src/razan_server.o

# target to build an object file
src/razan_server.cc.o:
	$(MAKE) -f CMakeFiles/razan_server.dir/build.make CMakeFiles/razan_server.dir/src/razan_server.cc.o
.PHONY : src/razan_server.cc.o

src/razan_server.i: src/razan_server.cc.i

.PHONY : src/razan_server.i

# target to preprocess a source file
src/razan_server.cc.i:
	$(MAKE) -f CMakeFiles/razan_server.dir/build.make CMakeFiles/razan_server.dir/src/razan_server.cc.i
.PHONY : src/razan_server.cc.i

src/razan_server.s: src/razan_server.cc.s

.PHONY : src/razan_server.s

# target to generate assembly for a file
src/razan_server.cc.s:
	$(MAKE) -f CMakeFiles/razan_server.dir/build.make CMakeFiles/razan_server.dir/src/razan_server.cc.s
.PHONY : src/razan_server.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... razan_client"
	@echo "... razan_server"
	@echo "... razan_client_chat"
	@echo "... razan_client_management"
	@echo "... razan_encryption"
	@echo "... razan_logger"
	@echo "... src/client_chat.o"
	@echo "... src/client_chat.i"
	@echo "... src/client_chat.s"
	@echo "... src/client_management.o"
	@echo "... src/client_management.i"
	@echo "... src/client_management.s"
	@echo "... src/encryption.o"
	@echo "... src/encryption.i"
	@echo "... src/encryption.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/razan_client.o"
	@echo "... src/razan_client.i"
	@echo "... src/razan_client.s"
	@echo "... src/razan_server.o"
	@echo "... src/razan_server.i"
	@echo "... src/razan_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

